version: '3.8'

services:
  db:
    image: mysql:8
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - /Users/danielzheng/Downloads/Development/ShowCompanyLogo/Docker/wordpress/wp-config.php:/var/www/html/wp-config.php
      - /Users/danielzheng/Downloads/Development/ShowCompanyLogo/Docker/wordpress/wp-content/uploads:/var/www/html/wp-content/plugins
      - /Users/danielzheng/Downloads/Development/ShowCompanyLogo/Docker/wordpress/wp-content/plugins:/var/www/html/wp-content/themes
      - /Users/danielzheng/Downloads/Development/ShowCompanyLogo/Docker/wordpress/wp-content/plugins:/var/www/html/wp-content/uploads
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network:
    driver: bridge
